apiVersion: v1
kind: Service
metadata:
  name: guestbook-stable
spec:
  type: LoadBalancer  
  ports:
  - name: guestbook
    port: 8080
  selector:
    app: guestbook-canary
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-canary
spec:
  ports:
  - name: guestbook
    port: 8080
  selector:
    app: guestbook-canary